---
title: "Summary"
author: "Izar de Villasante"
---

# Summary

In this project we tried to answer the following questions:

1. Is there an age-accelerating factor for XALD patients according to the changes in DNA methylation?

2. Which are the changes in DNA methylation associated with XALD disease?

To start with, we performed a [conventional analysis]() following our standard workflow for differential methylation analysis ( data preprocessing, filtering, identification of differentially methylated Probes,DMPs, and Regions, DMRs, and pathway analysis of the associated genes) using different sets of parameters (pvalu, FDR, min. methylation difference). Due to the imbalanced study design with a much smaller group of control vs disease cases and we repeated the same analysis including control cases from public datasets (GEO). 

1. Conventional analysis using standard pipline.

2. Conventional analysis including controls from GEO.

From this first approach we could identify some [enriched pathways](standard.qmd#sec-pathway) with genes associated with DMPs (individual probes). Nevertheless, by adding age to the model as a covariate this differences where lost.  

![Pathway analysis from genes associated to DMPs in model 2 (meth \~ 0 +
Condition).](data/pathways_m2_camd-cald.png){alt="Pathway analysis from genes associated to DMPs in model 2."}


Since the results from this conventional analysis where not satisfying we then tryed some other analysis replicating existing literature on DNA methylation associated with age:  

3. Checking for age-related signatures following the workflow described in @Steegenga2014

Here we saw some differences in methylation for our data for the set related with no change in gene expression.

```{r}
#| label: tbl-adult_z-test_residuals_model
#| tbl-cap: "Adult Disease vs Adult Controls methylation distributions significance test."
readRDS("data/ztab.rds")
```


~~4. Checking age acceleration as decribed by @Horvath2013~~


We identified a particular set of age-related genes that were differentially methylated for the XALD + cerebral condition in adult patients for specific sites that had been previously reported to be related with age.

See @tbl-adult_z-test_cov_model


2. We also identified the main pathways associated with the disease.


